openapi: 3.0.0
info:
  title: Documentación de SWAPI API reto técnico - Jorge Dominguez
  description: API para obtener datos de SWAPI y convertir sus atributos de inglés a español.
  version: 1.0.0
servers:
- url: https://h6ccp3l9qd.execute-api.us-east-1.amazonaws.com

paths:
  /peopleSwapi/{peopleNumber}:
    parameters:
      - in: path
        name: peopleNumber
        required: true
        schema:
          type: integer
          minimum: 1
        description: Número de la persona en SWAPI
    get:
      summary: Obtener la respuesta de la consulta de SWAPI API y convertir sus atributos de inglés a español.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: ID de la persona en SWAPI
                  name:
                    type: string
                    description: Nombre de la persona
                  height:
                    type: string
                    description: Altura de la persona
                  mass:
                    type: string
                    description: Masa de la persona
                  hair_color:
                    type: string
                    description: Color de cabello de la persona
                  skin_color:
                    type: string
                    description: Color de piel de la persona
                  eye_color:
                    type: string
                    description: Color de ojos de la persona
                  birth_year:
                    type: string
                    description: Año de nacimiento de la persona
                  gender:
                    type: string
                    description: Género de la persona
                  homeworld:
                    type: string
                    description: Planeta natal de la persona

    

  /createUser:
    post:
      summary: Crear un nuevo usuario
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  description: Nombre del usuario
                apellido:
                  type: string
                  description: Apellido del usuario
                profesion:
                  type: string
                  description: Profesión del usuario
              required:
                - nombre
                - apellido
                - profesion
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                    description: ID del usuario creado
                  nombre:
                    type: string
                    description: Nombre del usuario
                  apellido:
                    type: string
                    description: Apellido del usuario
                  profesion:
                    type: string
                    description: Profesión del usuario
                  createAt:
                    type: string
                    format: date-time
                    description: Fecha y hora de creación del usuario
        '500':
          description: Error interno del servidor
    
  /getUser:
    get:
      summary: Obtener la lista de usuarios
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: string
                      description: ID del usuario
                    nombre:
                      type: string
                      description: Nombre del usuario
                    apellido:
                      type: string
                      description: Apellido del usuario
                    profesion:
                      type: string
                      description: Profesión del usuario
                    createAt:
                      type: string
                      format: date-time
                      description: Fecha y hora de creación del usuario
        '500':
          description: Error interno del servidor
